export const Z_INDEX = {
  POPOVER_BARRIER: 50,
  POPOVER_CONTENT: 51,
  SHEET_BACKDROP: 100,
  SHEET_CONTENT: 101,
  DIALOG_BACKDROP: 200,
  DIALOG_CONTENT: 201,
  MOBILE_POPOVER_BACKDROP: 300,
  MOBILE_POPOVER_CONTENT: 301,
} as const;
